# Generated by Django 5.0.6 on 2024-05-30 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadai_0', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('treatmentid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('treatment_date', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(limit_choices_to={'emprole': 1}, on_delete=django.db.models.deletion.CASCADE, to='kadai_0.employee')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadai_0.medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadai_0.patient')),
            ],
        ),
    ]
