# Generated by Django 5.0.6 on 2024-06-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadai_0', '0002_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiiregyosha',
            name='shiiretel',
            field=models.CharField(max_length=15),
        ),
    ]
