# Generated by Django 5.0.6 on 2024-06-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadai_0', '0003_alter_shiiregyosha_shiiretel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabyouin',
            name='kyukyu',
            field=models.BooleanField(),
        ),
    ]
