# Generated by Django 5.0.6 on 2024-06-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadai_0', '0005_alter_tabyouin_tabyouintel_medicalrecord_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
